# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 63fca4b51bb4f3ab6cc55183ec50daeee6c0948f8227879613ebacd53cb9d3ce06b6013ddccf1a75c73efb80b2b4f9830b2e66e124cc2bda0b6adb078d9e0130

test:
  secret_key_base: 8f84a807f13f152b53a466af45f3194cdf8b75a3e771ee8b09e5055264406a3b85ebc5baa7b0978a8f3ef6b32e6b8b4fa1b32520cba808116574ef064b00c2d4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
